trigger:
  branches:
    include: [stage, main]

pool:
  name: 'GR_CLOUD_MEGA'

variables:
  DATABRICKS_CLI_DIR: 'D:\digic_gr_ai\databrickscli'

steps:
  - checkout: self

  # setup variables once
  - powershell: |
      $env:PATH = "$(DATABRICKS_CLI_DIR);$(PATH)"
      databricks.exe version

      if ("$(Build.SourceBranchName)" -eq "stage") {
        Write-Host "Using stage environment"
        Write-Output "##vso[task.setvariable variable=BUNDLE_TARGET]stage"
        Write-Output "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]$(DATABRICKS_STAGE_TOKEN)"
      }
      elseif ("$(Build.SourceBranchName)" -eq "main") {
        Write-Host "Using prod environment"
        Write-Output "##vso[task.setvariable variable=BUNDLE_TARGET]prod"
        Write-Output "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]$(DATABRICKS_PROD_TOKEN)"
      }
      else {
        Write-Host "Not a deployment branch"
        exit 1
      }
    name: setup
    displayName: 'Setup environment variables'

  # validate DAB bundle
  - powershell: |
      $env:PATH = "$(DATABRICKS_CLI_DIR);$(PATH)"
      databricks.exe bundle validate -t "$(BUNDLE_TARGET)" --debug
    displayName: 'Validate DAB bundle'
    env:
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  # deploy DAB bundle
  - powershell: |
      $env:PATH = "$(DATABRICKS_CLI_DIR);$(PATH)"
      databricks.exe bundle deploy -t "$(BUNDLE_TARGET)"
    displayName: 'Deploy DAB bundle'
    env:
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  # run jobs on deploy (this runs the database-init-job job of the databricks.yml file)
  - powershell: |
      $env:PATH = "$(DATABRICKS_CLI_DIR);$(PATH)"
      databricks.exe bundle run -t "$(BUNDLE_TARGET)" database-init-job
    displayName: 'Execute Jobs on deploy'
    env:
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)